/**
 * CommentOverlayCurrent — the REAL shipping comment overlay (static/comments.js)
 * running over the sample page, so the current interaction can be felt and compared.
 *
 * comments.js reads its config from document.currentScript.dataset and talks to
 * /api/viewer + /api/comments/*. We inject it as a real <script> (so currentScript
 * is set) and stub window.fetch to serve the mock viewer + threads and to mutate a
 * local thread array (create / reply / kind / resolve / delete all work, on mock state).
 * No backend, no real navigation.
 */
import { useEffect, useRef } from 'react';
import { ReviewPage } from './review-page';
import { HANDLE, PATH, SLUG, VIEWER, makeThreads, type PpThread } from './comment-fixtures';
// generated by prebundle.mjs from static/comments.js (default export = source string)
// @ts-expect-error generated module, no types
import COMMENTS_JS from './comments-source.generated.js';

export function CommentOverlayCurrent() {
  const ref = useRef<HTMLDivElement>(null);

  useEffect(() => {
    const threads: PpThread[] = makeThreads();
    const origFetch = window.fetch;
    const rid = () => 'x' + Math.random().toString(36).slice(2, 12);
    const json = (obj: unknown, status = 200) =>
      new Response(status === 204 ? null : JSON.stringify(obj), {
        status,
        headers: { 'Content-Type': 'application/json' },
      });

    window.fetch = (async (input: RequestInfo | URL, init?: RequestInit) => {
      const url = typeof input === 'string' ? input : input instanceof URL ? input.href : input.url;
      const method = (init?.method || 'GET').toUpperCase();
      const path = url.replace(/^https?:\/\/[^/]+/, '');
      const body = init?.body ? JSON.parse(String(init.body)) : {};
      let m: RegExpMatchArray | null;

      if (path.startsWith('/api/viewer')) return json(VIEWER);
      if (/^\/api\/comments\/[^/]+\/[^/]+(\?|$)/.test(path) && method === 'GET') return json({ threads });
      if (/^\/api\/comments\/[^/]+\/[^/]+/.test(path) && method === 'POST') {
        const t: PpThread = {
          id: rid(),
          selector: body.selector,
          rx: body.rx,
          ry: body.ry,
          rw: body.rw ?? null,
          rh: body.rh ?? null,
          kind: body.kind ?? null,
          resolved: false,
          page_path: body.path ?? PATH,
          anchor_text: body.anchor_text ?? null,
          comments: [
            { id: rid(), author_sub: VIEWER.sub, author_name: VIEWER.name, text: body.text, created_at: new Date().toISOString() },
          ],
        };
        threads.push(t);
        return json(t);
      }
      if ((m = path.match(/^\/api\/comments\/threads\/([^/]+)\/replies$/)) && method === 'POST') {
        const t = threads.find((x) => x.id === m![1]);
        if (t) t.comments.push({ id: rid(), author_sub: VIEWER.sub, author_name: VIEWER.name, text: body.text, created_at: new Date().toISOString() });
        return json(t ?? {});
      }
      if ((m = path.match(/^\/api\/comments\/threads\/([^/]+)$/)) && method === 'PATCH') {
        const t = threads.find((x) => x.id === m![1]);
        if (t) Object.assign(t, body);
        return json(t ?? {});
      }
      if ((m = path.match(/^\/api\/comments\/threads\/([^/]+)$/)) && method === 'DELETE') {
        const i = threads.findIndex((x) => x.id === m![1]);
        if (i !== -1) threads.splice(i, 1);
        return json(null, 204);
      }
      return origFetch(input as RequestInfo, init);
    }) as typeof window.fetch;

    // inject the real overlay as a script (sets document.currentScript for its CFG)
    (window as Record<string, unknown>).__ppAnnoLoaded = false;
    const s = document.createElement('script');
    s.dataset.handle = HANDLE;
    s.dataset.slug = SLUG;
    s.dataset.path = PATH;
    s.dataset.version = 'v1';
    s.textContent = COMMENTS_JS as string;
    document.body.appendChild(s);

    return () => {
      window.fetch = origFetch;
      s.remove();
      document
        .querySelectorAll('.pp-anno-root, [data-pp-anno], .pp-anno-bar, .pp-anno-toast')
        .forEach((n) => n.remove());
      document.querySelectorAll('head style').forEach((st) => {
        if (st.textContent && st.textContent.includes('.pp-anno-root')) st.remove();
      });
      (window as Record<string, unknown>).__ppAnnoLoaded = false;
    };
  }, []);

  return (
    <div ref={ref}>
      <ReviewPage />
    </div>
  );
}
